import Image from 'next/image';
import './globals.scss';

export const metadata = {
  title: 'Creating Netflix app',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header>
        <div className="logo">
          {/* <Image src="https://about.netflix.com/images/logo.png" width="200" height="200" alt="logo" /> */}
        </div>
        <div className="menu"></div>
      </header>
      <body>{children}</body>
    </html>
  );
}
